data:
  columns: &id001
  - bedrooms
  - bathrooms
  - sqft_living
  - sqft_lot
  - floors
  - waterfront
  - view
  - condition
  - grade
  - sqft_above
  - sqft_basement
  - yr_built
  - yr_renovated
  - lat
  - long
  - sqft_living15
  - sqft_lot15
  - house_age
  dependent_var: price
  filepath: E:/DataAnalysisTool/notebook/data/kc_house_data.csv
  independent_vars: *id001
model:
  ann:
    batch_size: 128
    epochs: 400
    input_shape: 19
    layers:
    - activation: relu
      units: 19
    - activation: relu
      units: 19
    - activation: relu
      units: 19
    - activation: relu
      units: 19
    loss: mse
    metrics:
    - mean_squared_error
    optimizer: adam
  decision_tree:
    max_depth: 9
    random_state: 42
  type: ANN
prediction:
  new_gem:
  - 998
  - 1000
saved_model:
  filepath: model.h5
