data:
  filepath: "E:/DataAnalysisTool/notebook/data/fake_reg.csv"

model:
  input_shape: 2
  layers:
    - units: 4
      activation: "relu"
    - units: 4
      activation: "relu"
    - units: 4
      activation: "relu"
    - units: 1
      activation: null
  optimizer: "rmsprop"
  loss: "mse"
  metrics: ["mse"]  # Additional metrics can be added here, like ['accuracy'] for classification
  epochs: 250

test_size: 0.3
random_state: 42

prediction:
  new_gem: [[998, 1000]]

saved_model:
  filepath: "my_model.h5"
